# The character that hides regular messages from the console to avoid spam from emoji forming characters
# This should only be a single character and should not be one visible in the console
# By default this is the 'null' character \u0000 but you can change it if you encounter any issues
# Alternative options:
# - '' \uF004
# - '' \uF005
# - '' \uF006
# Other characters may be used, but require the resource pack to be modified
filter-flag: ''

# Whether to use the default resource pack - this is required for emojis, but you may wish to disable it in order to add custom filter flags,
# Or to merge it with your own pack. The default pack can be found at https://github.com/cometcake575/EmojiCrafter/raw/main/EmojiPack.zip
use-resource-pack: true
